title: Tom치코 Valenta
email: semanticer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The most interesting personal blog in the universe.
  Mainly about software development, music making, meditation and your mom!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tomasvalenta.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite:
  name: Tom치코 Valenta
  tagline: |
    Android Developer
      Music Producer
  date_format: "%b %-d, %Y"
  

  social_links:
    twitter: Semantic_Error
    github: semanticer
    linkedIn: in/tomasvalenta/ # format: locale/username
#  navigation:
#    - title: My Work
#      url: "/my-work"
#    - title: Resume
#      url: "/resume"
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
